import mongoose, { Schema, Document } from 'mongoose';

/**
 * Preference Schema
 * 
 * Represents user property preferences for Buy, Rent, Joint Venture, and Shortlet
 * This schema is designed to auto-populate Property documents when a preference is submitted
 */

// Contact Info Interface
interface IContactInfo {
  fullName?: string;
  companyName?: string;
  contactPerson?: string;
  email: string;
  phoneNumber: string;
  cacRegistrationNumber?: string;
}

// Location Interface
interface ILocation {
  state: string;
  lgas: string[];
  areas?: string[];
  customLocation?: string;
}

// Budget Interface
interface IBudgetRange {
  minPrice: number;
  maxPrice: number;
  currency: string;
}

// Feature Selection Interface
interface IFeatureSelection {
  basicFeatures: string[];
  premiumFeatures: string[];
  autoAdjustToBudget: boolean;
}

// Property Details for Buy
interface IBuyPropertyDetails {
  propertySubtype: 'land' | 'residential' | 'commercial';
  buildingType?: 'detached' | 'semi-detached' | 'block-of-flats';
  minBedrooms?: number | 'More';
  minBathrooms?: number;
  propertyCondition?: 'new' | 'renovated' | 'old';
  purpose?: 'for-living' | 'resale' | 'development';
  measurementUnit?: 'plot' | 'sqm' | 'hectares';
  landSize?: number;
  documentTypes?: string[];
}

// Property Details for Rent
interface IRentPropertyDetails {
  propertySubtype: 'self-con' | 'flat' | 'mini-flat' | 'bungalow';
  minBedrooms?: number | 'More';
  minBathrooms?: number;
  leaseTerm?: '6-months' | '1-year';
  propertyCondition?: 'new' | 'renovated';
  purpose?: 'residential' | 'office';
}

// Development Details for Joint Venture
interface IDevelopmentDetails {
  minLandSize: string;
  measurementUnit: 'plot' | 'sqm' | 'hectares';
  propertyType?: 'land' | 'old-building' | 'structure-to-demolish';
  expectedStructureType?: string;
  jvType?: 'equity-split' | 'lease-to-build' | 'development-partner';
  timeline?: 'ready-now' | 'in-3-months' | 'within-1-year';
  budgetRange?: number;
  landConditions?: string[];
  preferredSharingRatio?: string;
  minimumTitleRequirements?: string[];
  developmentTypes?: string[];
}

// Booking Details for Shortlet
interface IBookingDetails {
  propertyType?: 'studio' | '1-bed' | '2-bed';
  minBedrooms?: number | 'More';
  numberOfGuests?: number;
  checkInDate?: string;
  checkOutDate?: string;
}

// Base Preference Document
interface IPreference extends Document {
  userId: string;
  preferenceType: 'buy' | 'rent' | 'joint-venture' | 'shortlet';
  preferenceMode: 'buy' | 'tenant' | 'developer' | 'shortlet';
  
  // Common fields
  location: ILocation;
  budget: IBudgetRange;
  features: IFeatureSelection;
  contactInfo: IContactInfo;
  
  // Conditional fields based on preferenceType
  propertyDetails?: IBuyPropertyDetails | IRentPropertyDetails;
  developmentDetails?: IDevelopmentDetails;
  bookingDetails?: IBookingDetails;
  
  // Additional info
  nearbyLandmark?: string;
  additionalNotes?: string;
  partnerExpectations?: string;
  
  // Status tracking
  status: 'active' | 'paused' | 'fulfilled' | 'expired';
  matchedPropertiesCount: number;
  
  // Metadata
  createdAt: Date;
  updatedAt: Date;
  expiresAt?: Date;
  
  // For auto-population tracking
  autoGeneratedProperties?: string[]; // Array of Property IDs auto-generated from this preference
}

// Contact Info Schema
const contactInfoSchema = new Schema({
  fullName: {
    type: String,
    trim: true,
    maxlength: 100,
  },
  companyName: {
    type: String,
    trim: true,
    maxlength: 200,
  },
  contactPerson: {
    type: String,
    trim: true,
    maxlength: 100,
  },
  email: {
    type: String,
    required: true,
    lowercase: true,
    trim: true,
    maxlength: 255,
    match: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  },
  phoneNumber: {
    type: String,
    required: true,
    trim: true,
  },
  cacRegistrationNumber: {
    type: String,
    trim: true,
    maxlength: 50,
  },
}, { _id: false });

// Location Schema
const locationSchema = new Schema({
  state: {
    type: String,
    required: true,
    trim: true,
  },
  lgas: {
    type: [String],
    required: true,
    validate: {
      validator: function(v: string[]) {
        return v && v.length > 0 && v.length <= 3;
      },
      message: 'LGAs must have between 1 and 3 items',
    },
  },
  areas: {
    type: [String],
    validate: {
      validator: function(v: string[]) {
        return !v || v.length <= 3;
      },
      message: 'Maximum 3 areas allowed',
    },
  },
  customLocation: {
    type: String,
    trim: true,
    maxlength: 200,
  },
}, { _id: false });

// Budget Range Schema
const budgetSchema = new Schema({
  minPrice: {
    type: Number,
    required: true,
    min: 0,
  },
  maxPrice: {
    type: Number,
    required: true,
    min: 0,
    validate: {
      validator: function(this: any, v: number) {
        return v > this.minPrice;
      },
      message: 'Max price must be greater than min price',
    },
  },
  currency: {
    type: String,
    default: 'NGN',
    enum: ['NGN', 'USD', 'GBP'],
  },
}, { _id: false });

// Feature Selection Schema
const featureSelectionSchema = new Schema({
  basicFeatures: {
    type: [String],
    default: [],
  },
  premiumFeatures: {
    type: [String],
    default: [],
  },
  autoAdjustToBudget: {
    type: Boolean,
    default: false,
  },
}, { _id: false });

// Buy Property Details Schema
const buyPropertyDetailsSchema = new Schema({
  propertySubtype: {
    type: String,
    enum: ['land', 'residential', 'commercial'],
    required: true,
  },
  buildingType: {
    type: String,
    enum: ['detached', 'semi-detached', 'block-of-flats', null],
  },
  minBedrooms: {
    type: Schema.Types.Mixed,
    validate: {
      validator: function(v: any) {
        return v === 'More' || (typeof v === 'number' && v >= 1 && v <= 10);
      },
      message: 'Min bedrooms must be a number 1-10 or "More"',
    },
  },
  minBathrooms: Number,
  propertyCondition: {
    type: String,
    enum: ['new', 'renovated', 'old', null],
  },
  purpose: {
    type: String,
    enum: ['for-living', 'resale', 'development', null],
  },
  measurementUnit: {
    type: String,
    enum: ['plot', 'sqm', 'hectares', null],
  },
  landSize: Number,
  documentTypes: {
    type: [String],
    default: [],
  },
}, { _id: false });

// Rent Property Details Schema
const rentPropertyDetailsSchema = new Schema({
  propertySubtype: {
    type: String,
    enum: ['self-con', 'flat', 'mini-flat', 'bungalow'],
    required: true,
  },
  minBedrooms: {
    type: Schema.Types.Mixed,
    validate: {
      validator: function(v: any) {
        return v === 'More' || (typeof v === 'number' && v >= 1 && v <= 10);
      },
      message: 'Min bedrooms must be a number 1-10 or "More"',
    },
  },
  minBathrooms: Number,
  leaseTerm: {
    type: String,
    enum: ['6-months', '1-year'],
  },
  propertyCondition: {
    type: String,
    enum: ['new', 'renovated', 'good-condition', null],
  },
  purpose: {
    type: String,
    enum: ['residential', 'office', null],
  },
}, { _id: false });

// Development Details Schema (Joint Venture)
const developmentDetailsSchema = new Schema({
  minLandSize: {
    type: String,
    required: true,
  },
  measurementUnit: {
    type: String,
    enum: ['plot', 'sqm', 'hectares'],
    required: true,
  },
  propertyType: {
    type: String,
    enum: ['land', 'old-building', 'structure-to-demolish', null],
  },
  expectedStructureType: String,
  jvType: {
    type: String,
    enum: ['equity-split', 'lease-to-build', 'development-partner', null],
  },
  timeline: {
    type: String,
    enum: ['ready-now', 'in-3-months', 'within-1-year', null],
  },
  budgetRange: Number,
  landConditions: {
    type: [String],
    default: [],
  },
  preferredSharingRatio: String,
  minimumTitleRequirements: {
    type: [String],
    default: [],
  },
  developmentTypes: {
    type: [String],
    default: [],
  },
}, { _id: false });

// Booking Details Schema (Shortlet)
const bookingDetailsSchema = new Schema({
  propertyType: {
    type: String,
    enum: ['studio', '1-bed', '2-bed', null],
  },
  minBedrooms: {
    type: Schema.Types.Mixed,
    validate: {
      validator: function(v: any) {
        return v === 'More' || (typeof v === 'number' && v >= 0 && v <= 10);
      },
      message: 'Min bedrooms must be a number 0-10 or "More"',
    },
  },
  numberOfGuests: {
    type: Number,
    min: 1,
  },
  checkInDate: Date,
  checkOutDate: Date,
}, { _id: false });

// Main Preference Schema
const PreferenceSchema = new Schema<IPreference>(
  {
    userId: {
      type: String,
      required: true,
      index: true,
    },
    preferenceType: {
      type: String,
      enum: ['buy', 'rent', 'joint-venture', 'shortlet'],
      required: true,
      index: true,
    },
    preferenceMode: {
      type: String,
      enum: ['buy', 'tenant', 'developer', 'shortlet'],
      required: true,
    },
    location: {
      type: locationSchema,
      required: true,
    },
    budget: {
      type: budgetSchema,
      required: true,
    },
    features: {
      type: featureSelectionSchema,
      default: () => ({
        basicFeatures: [],
        premiumFeatures: [],
        autoAdjustToBudget: false,
      }),
    },
    contactInfo: {
      type: contactInfoSchema,
      required: true,
    },
    propertyDetails: {
      type: Schema.Types.Mixed,
    },
    developmentDetails: {
      type: developmentDetailsSchema,
    },
    bookingDetails: {
      type: bookingDetailsSchema,
    },
    nearbyLandmark: {
      type: String,
      trim: true,
      maxlength: 200,
    },
    additionalNotes: {
      type: String,
      trim: true,
      maxlength: 1000,
    },
    partnerExpectations: {
      type: String,
      trim: true,
      maxlength: 1000,
    },
    status: {
      type: String,
      enum: ['active', 'paused', 'fulfilled', 'expired'],
      default: 'active',
      index: true,
    },
    matchedPropertiesCount: {
      type: Number,
      default: 0,
    },
    expiresAt: {
      type: Date,
      index: true,
    },
    autoGeneratedProperties: {
      type: [String],
      default: [],
    },
  },
  {
    timestamps: true,
  }
);

// Indexes for optimized queries
PreferenceSchema.index({ userId: 1, preferenceType: 1 });
PreferenceSchema.index({ 'location.state': 1, preferenceType: 1 });
PreferenceSchema.index({ status: 1, expiresAt: 1 });
PreferenceSchema.index({ createdAt: -1 });

// Export
export default mongoose.model<IPreference>('Preference', PreferenceSchema);
export { IPreference, IContactInfo, ILocation, IBudgetRange, IFeatureSelection };
