/** @format */
/** @format */

import type { Metadata } from 'next';
//import { Roboto } from 'next/font/google';
import '@/app/globals.css';
import { PageContextProvider } from '@/context/page-context';

export const metadata: Metadata = {
  title: 'Khabiteq | Buy',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <PageContextProvider>{children}</PageContextProvider>;
}
