/** @format */

export const URLS = {
  BASE: `${process.env.NEXT_PUBLIC_API_URL}`,
  agent: '/agent',
  agentSignup: '/agent/signup',
  agentLogin: '/agent/login',
  uploadImg: '/upload-image',
  agentOnboarding: '/agent/onboard',
  agentProfile: '/agent/profile',
  googleSignup: '/signup/google',
  googleLogin: '/login/google',
  verifyEmail: '/verify-email',
  agentCreateBrief: '/properties/sell/new',
  agentfetchTotalBriefs: '/agent/properties',
  landLordCreateBrief: '/properties/rents/rent/new',
  buyersFetchBriefs: '/properties/sell/all',
  rentersFetchBriefs: '/properties/rents/all', 
  buyersSearchBrief: '/properties/buy/request/search',
  resetPassword: '/reset-password',
  requestPasswordReset: '/request-password-reset',
  allAvailableSLots: '/all/inspection-slots',
  scheduleInspection: '/property/schedule-inspection',
  getAllRequests: '/requests',
  confirmAvailability: '/confirm-property',
  agentGetUserPreferences: '/agent/preferences',
  agentApproval: '/admin/approve-agent',
  getAllAgents: '/admin/all-agents',
  changePassword: '/agent/change-password',
  upgradeAccount: '/agent/account-upgrade',
  userAccount: '/agent/account',
  adminGetAllInspections: '/admin/request/all',
  approveBrief: '/admin/approve-disapprove-property',
  deleteBrief: '/api/briefs/delete',
  rejectBrief: '/api/briefs/reject',
  adminGetAllBriefs: '/admin/properties',
};
