/** @format */

export const URLS = {
  BASE: process.env.NEXT_PUBLIC_API_URL || "https://api.khabiteq.com",
  agent: "/agent",
  user: "/user",
  userProfile: "/me",
  userSignup: "/user/signup",
  userLogin: "/user/login",
  login: "/login",
  uploadImg: "/upload-image",
  agentOnboarding: "/agent/onboard",
  agentProfile: "/agent/profile",
  googleSignup: "/signup/google",
  googleLogin: "/login/google",
  facebookSignup: "/signup/facebook",
  facebookLogin: "/login/facebook",
  verifyEmail: "/verify-email",
  resendVerification: "/resend-verification",
  agentCreateBrief: "/properties/sell/new",
  listNewProperty: "/properties/new",
  userSubmitPreference: "/properties/preference/new",
  getMyProperties: "/properties/mine/all",
  getOneProperty: "/properties/",
  agentfetchTotalBriefs: "/agent/properties",
  landLordCreateBrief: "/properties/rents/rent/new",
  buyersFetchBriefs: "/properties/all",
  fetchBriefs: "/properties/all",
  rentersFetchBriefs: "/properties/rents/all",
  buyersSearchBrief: "/properties/buy/request/search",
  searchBrief: "/properties/search",
  resetPassword: "/reset-password",
  requestPasswordReset: "/request-password-reset",
  allAvailableSLots: "/all/inspection-slots",
  scheduleInspection: "/property/schedule-inspection",

  requestInspection: "/inspections/request-inspection",
  validateInspectionAccess: "/inspections/validate-access",
  getOneInspection: "/inspections/inspection-details",
  negotiationActions: "/inspections",

  updateInspection: "/buyers/update-inspection",
  getOneNewInspection: "/buyers/new-inspection",

  getAllRequests: "/requests",
  confirmAvailability: "/confirm-property",
  agentGetUserPreferences: "/agent/preferences",
  changePassword: "/agent/change-password",
  upgradeAccount: "/agent/account-upgrade",
  userAccount: "/agent/account",
  deleteBrief: "/api/briefs/delete",
  rejectBrief: "/api/briefs/reject",
  deleteSellBrief: "/properties/sell/delete/",
  getAllPreferences: "/properties/preference",
  getAllPropertySells: "/properties/sell/all",
  getAllBuyersPreference: "/agent/all-preferences",
  submitBuyerPreference: "/buyers/submit-preference",
  postProperty: "/properties/new",
};
