/** @format */
/** @format */

import type { Metadata } from 'next';
import '@/app/globals.css';
import { PageContextProvider } from '@/context/page-context';

export const metadata: Metadata = {
  title: 'Khabiteq | About Us',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <PageContextProvider>{children}</PageContextProvider>;
}
