/** @format */
/** @format */

import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import '@/app/globals.css';
import { PageContextProvider } from '@/context/page-context';
import Header from '@/components/header';
import Footer from '@/components/footer';
//import Head from 'next/head';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['400', '700'], // Specify weights you want to use (optional)
});

export const metadata: Metadata = {
  title: 'Khabiteq | About Us',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PageContextProvider>
      <html lang='en'>
        <body className={`${roboto.variable} antialiased`}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </PageContextProvider>
  );
}
